name: CI

on:
  workflow_call:
  release:
    types:
      - published

jobs:
  determine-version:
    uses: ./.github/workflows/reusable-determine-version.yml

  base-build:
    needs: determine-version
    uses: ./.github/workflows/reusable-base-build.yml

  android-build:
    needs: [determine-version, base-build]
    uses: ./.github/workflows/reusable-android-build.yml
    secrets: inherit
    with:
      version: ${{ needs.determine-version.outputs.version }}
      base-build-artifact-name: ${{ needs.base-build.outputs.artifact_name }}

  attach-android-artifacts-to-release:
    if: github.event_name == 'release'
    needs: android-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Android build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.android-build.outputs.artifact_name }}
          path: release-artifacts
      - name: Rename Android artifacts
        run: |
          mv release-artifacts/apk/release/app-release.apk release-artifacts/macro-deck-client-android.apk
          mv release-artifacts/bundle/release/app-release.aab release-artifacts/macro-deck-client-android.aab
      - name: Attach Android artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name || github.ref_name }}
          files: |
            release-artifacts/macro-deck-client-android.apk
            release-artifacts/macro-deck-client-android.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
